feature/adding event hubs output plugin
grafana/k6 pull request #1755
Opened 2020-12-06 15:06 UTC by polatengin

Allow using Azure Event Hubs as an output target, so you can use `--output eventhubs` to fork k6 outputs to Azure Event Hubs.

2020-12-06 15:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/loadimpact/k6?pullRequest=1755) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/loadimpact/k6?pullRequest=1755) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/loadimpact/k6?pullRequest=1755) it.</sub>

2020-12-08 15:38 UTC, imiric requested changes
Thanks for proposing this @polatengin! I left a few minor comments, and the testing situation should be improved before we consider merging this.

Also make sure to run `go mod vendor` / `go mod tidy` and commit the changes, otherwise you won't get a passing build in CI.

The k6 team is not familiar with Azure Event Hubs, but from what I could gather [it exposes a Kafka-compliant endpoint](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-quickstart-kafka-enabled-event-hubs). Is there a reason why the current [Kafka output](https://k6.io/docs/results-visualization/apache-kafka) or the new [Kafka extension](https://github.com/mostafa/xk6-kafka) couldn't be used instead of adding a custom collector for it?

It also appears to be based on [AMQP](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-amqp-protocol-guide), which is a much more generic and widely used protocol. From that perspective it would be preferable if we added AMQP support instead (say, as a new k6 extension), which would close #1073, and supported Event Hubs that way.

I'm interested to hear your thoughts on this, and also from @na-- @MStoykov.

2020-12-08 15:38 UTC, imiric commented on stats/eventhubs/config.go
> +* Copyright (C) 2017 Load Impact
```suggestion
* Copyright (C) 2020 Load Impact
```

2020-12-08 15:38 UTC, imiric commented on stats/eventhubs/config.go
> +		PushInterval:     types.NewNullDuration(1*time.Second, false),
We should keep the `Valid` value consistent for these null types, so maybe:

```suggestion
		ConnectionString: null.NewString("", false),
		BufferEnabled:    null.NewBool(true, false),
		PushInterval:     types.NewNullDuration(1*time.Second, false),
```

I would prefer to see a usable default value for `ConnectionString`, but apparently Event Hubs can't be started locally, so I guess this is fine.

2020-12-08 15:38 UTC, imiric commented on stats/eventhubs/config.go
> +
```suggestion
```

2020-12-08 15:38 UTC, imiric commented on stats/eventhubs/config_test.go
> + * Copyright (C) 2016 Load Impact
```suggestion
 * Copyright (C) 2020 Load Impact
```

2020-12-08 15:38 UTC, imiric commented on stats/eventhubs/config_test.go
> +	assert.Equal(t, sql.NullString(sql.NullString{String: "", Valid: true}), config.ConnectionString.NullString)
No need to import `sql` here, no?

```suggestion
	assert.Equal(t, null.NewString("", false), config.ConnectionString)
```

2020-12-08 15:57 UTC, na-- commented
I don't have the time to look at this PR closely right now, sorry... I am also not very familiar with Azure Event Hubs or Application Insights (https://github.com/loadimpact/k6/pull/1757). But, in general, if we can use a generic open protocol to output metrics to some service, there needs to be a good reason not to use it and instead to use a custom SDK for it (https://github.com/Azure/azure-event-hubs-go in this case, from what I can see). Moreover, that dependency itself [seems to depend](https://github.com/Azure/azure-event-hubs-go#using-event-hubs) on a [dead library](https://github.com/vcabbage/amqp#packagamqp)... :confused: 

In any case, I also wanted to say that we plan to majorly refactor how the k6 outputs are handled, currently targeting k6 v0.31.0 (Feb 2021). We aim to fix a bunch of issues (https://github.com/loadimpact/k6/issues/1606, https://github.com/loadimpact/k6/issues/1075, https://github.com/loadimpact/k6/issues/1423 among others) and to also enable the addition of output extensions with [xk6](https://github.com/k6io/xk6). So it's very unlikely that we'll merge this PR or https://github.com/loadimpact/k6/pull/1757 before k6 v0.31.0. And even then, I can't promise that these outputs would be merged straight into the k6 core, they might be better off as extensions for a while, to mature. We'd need to gauge the user interest against the maintenance burden of such changes.

2020-12-09 11:32 UTC, simskij commented
I can assist here if it's any help, @na--. I'm quite familiar with Azure 👍

2020-12-15 13:06 UTC, polatengin commented
> I can assist here if it's any help, @na--. I'm quite familiar with Azure 👍

Hi @simskij thanks for your support offer. It's greatly appreciated 👍

2020-12-15 13:10 UTC, polatengin commented
> In any case, I also wanted to say that we plan to majorly refactor how the k6 outputs are handled, currently targeting k6 v0.31.0 (Feb 2021). We aim to fix a bunch of issues (#1606, #1075, #1423 among others) and to also enable the addition of output extensions with [xk6](https://github.com/k6io/xk6). So it's very unlikely that we'll merge this PR or #1757 before k6 v0.31.0

Hey @na-- , is there an `Early Access` program for the new output system with xk6? I'd like to be in such program if you have one, also please count me in if you're going to do some design sessions and looking for community contributions.

2020-12-15 18:02 UTC, imiric commented
@polatengin There's no "Early Access" program for xk6, but you're welcome to try creating an extension and publishing it on GitHub. Proper documentation is still pending, but you can take a look at [this article](https://k6.io/blog/extending-k6-with-xk6), and use [existing extensions](https://github.com/topics/xk6) as examples. It's really quite straightforward :)

If you need any help or have any suggestions feel free to post on [the forum](https://community.k6.io/) or [Slack](https://k6.io/slack).

2022-03-31 08:08 UTC, MStoykov commented
Hi @polatengin , thanks for this PR :bow:. 

k6 has had support for output extensions for some time now. As of today it also has a [template repo for output extensions](https://github.com/grafana/xk6-output-template). This plus all the other extension outputs should be enough for people to extract this code in an extension and use it without it being in k6 core.

Given that I am closing this PR.

2022-03-31 08:08 UTC, closed without merging