feature/adding application insights output plugin
grafana/k6 pull request #1757
Opened 2020-12-06 15:28 UTC by polatengin

Allow using Application Insights as an output target, so you can use --output appinsights to fork k6 outputs to Application Insights.

2020-12-08 22:11 UTC, rguthriemsft requested changes
Need to add an appinsights_test.go file with test for the collector.

2020-12-08 22:11 UTC, rguthriemsft commented on stats/appinsights/config.go
> +			return c, fmt.Errorf("couldn't parse %q as argument for csv output", arg)
This error message looks incorrect, should it be "for appinsights output" instead of csv output.

2020-12-08 22:11 UTC, rguthriemsft commented on stats/appinsights/config.go
> +			return c, fmt.Errorf("unknown key %q as argument for csv output", r[0])
same as above.

2020-12-15 14:12 UTC, mostafa commented
Hey @polatengin,

thanks for the output and the PR :pray:. I've done acceptance testing and it works fine. Yet, there are three things you might do before the PR is mergeable, which should be decided by the k6 Team (not me), considering the roadmap and other related things:

1. Please consider rebasing from the latest master.
2. @rguthriemsft left good reviews :pray:. Please consider addressing them.
3. Upon testing, I found that the namespace sent to App Insights is `azure.applicationinsights`. Is it possible to change it to `k6` instead? I am not sure if it is configurable via the Go library you've used. Yet, since I am adding a new integration for Azure Monitor on our Cloud service ([Cloud APM](https://k6.io/docs/cloud/integrations/cloud-apm)), I can set a custom namespace while sending custom metrics to Azure Monitor. So I suspect it might be configurable. I mean the `Metric Namespace` in the screenshot below.
![image](https://user-images.githubusercontent.com/54546/102225802-e6792a80-3ee7-11eb-8f36-038f1bd72e57.png)

2021-11-18 08:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/k6?pullRequest=1757) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/k6?pullRequest=1757) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/k6?pullRequest=1757) it.</sub>

2022-03-31 08:08 UTC, MStoykov commented
Hi @polatengin , thanks for this PR :bow:. 

k6 has had support for output extensions for some time now. As of today it also has a [template repo for output extensions](https://github.com/grafana/xk6-output-template). This plus all the other extension outputs should be enough for people to extract this code in an extension and use it without it being in k6 core.

Given that I am closing this PR.

2022-03-31 08:08 UTC, closed without merging