Fix grammar in the documentation
grafana/k6 pull request #2213
Opened 2021-10-31 15:59 UTC by wanderer163

2021-10-31 15:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/k6?pullRequest=2213) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/k6?pullRequest=2213) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/k6?pullRequest=2213) it.</sub>

2021-11-01 08:31 UTC, inancgumus approved these changes
Thanks! LGTM.

2021-11-01 13:22 UTC, FloorD commented
Hey @wanderer163 👋 we would love to send you a little k6 swag pack as per "thank you" for contributing to k6 this hacktoberfest. Please send your address details to floor[at]grafana.com and I'll take care it's shipped asap.

2021-11-02 07:37 UTC, na-- requested changes

2021-11-07 16:53 UTC, wanderer163 commented on README.md
> +Checks and thresholds are some k6 features that make it very easy to use load tests like unit and functional tests and integrate them in a CI (continuous integration) workflow.
Reverted this.

2021-11-08 06:48 UTC, na-- approved these changes

2021-11-11 08:31 UTC, codebien approved these changes
LGTM, thanks!

2021-11-11 09:36 UTC, yorugac approved these changes

2021-11-11 09:37 UTC, yorugac commented
CI failure is because of recent TLS issue which was already fixed in master.

2021-11-11 09:38 UTC, merged