js/k6: ModuleV2 migration
grafana/k6 pull request #2242
Opened 2021-11-16 13:47 UTC by codebien

Migrated `k6` to the `modules.Module` (aka `modules.ModuleV2`) interface.

2021-11-16 13:59 UTC, MStoykov commented on js/modules/k6/k6.go
> +	return modules.Exports{Default: mi.obj}
I would argue this should set only `Named` and then you can also drop the `obj` and have the map inlined here similar to 
https://github.com/grafana/k6/blob/3a604bf408ec278f71da2f577c76edc7778aece2/js/modules/k6/metrics/metrics.go#L162-L171

After all I would expect that users will use that as `import { sleep } from "k6";sleep()` not as `import k6 from "k6"; k6.sleep()`

2021-11-17 11:23 UTC, yorugac requested changes

2021-11-17 11:23 UTC, yorugac commented on js/modules/k6/k6_test.go
> +			CtxField:     common.WithRuntime(ctx, rt),
Here `common.WithRuntime` is called twice: at L225 and at L232. Shouldn't it be twice?

2021-11-22 15:43 UTC, MStoykov approved these changes

2021-11-22 18:12 UTC, merged