update iter/s precision from 0 to 2
grafana/k6 pull request #2282
Opened 2021-12-02 18:48 UTC by m3hm3t

This Pull Request addresses issue 1753.

If you set up a scenario where the executors run less than one iteration per second, the value is floored to zero while in progress.

By this PR, the behavior changes like at the below.

From:
![image](https://user-images.githubusercontent.com/22320354/144484045-85bedfd9-2a16-49cf-a23c-8f00c35e065f.png)

To:
![image](https://user-images.githubusercontent.com/22320354/144483815-29bce88b-2acc-4576-9917-1ea3c96f0ec1.png)

2021-12-02 18:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/k6?pullRequest=2282) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/k6?pullRequest=2282) before we can accept your contribution.<br/><hr/>**Mehmet Yilmaz** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/k6?pullRequest=2282) it.</sub>

2021-12-03 08:57 UTC, MStoykov commented
Hi @m3hm3t thanks for the PR, unfortunately, this was already kind of tried in https://github.com/grafana/k6/pull/1766. 

And as I mention [there](https://github.com/grafana/k6/pull/1766#issuecomment-746019781) it looks really strange with `ramping-arrival-rate` and big timeUnit. I don't think we have agreed on my suggestion, but maybe you can experiment with it? @DarkAEther seems to have not had time (which is completely understandable) do to so, so it's fine if somebody else does :).

2021-12-03 10:19 UTC, m3hm3t commented
Thanks for the comment @MStoykov. I will look into it.

2021-12-03 14:28 UTC, codebien requested changes
Setting the status as request changes

2022-05-12 12:21 UTC, mstoykov commented
After some internal discussion we have agreed that having this is probably better than nothing. Also some people have pointed out that changing the timeUnit shown will likely be more confusing than anything else.

2022-05-12 12:23 UTC, mstoykov approved these changes
LGTM! thanks for the PR and sorry for the really long delay :(

2022-05-16 13:47 UTC, oleiade approved these changes
👍🏻 🦕

2022-05-18 13:11 UTC, merged