Fix errors in README.md
grafana/k6 pull request #2617
Opened 2022-07-25 18:24 UTC by AMetIR

2022-07-25 18:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/k6?pullRequest=2617) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/k6?pullRequest=2617) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/k6?pullRequest=2617) it.</sub>

2022-07-26 11:36 UTC, MattDodsonEnglish commented on README.md
> +- **TLS features**: [client certificates](https://k6.io/docs/using-k6/protocols/ssl-tls/ssl-tls-client-certificates), [configurable SSL/TLS versions, and ciphers](https://k6.io/docs/using-k6/protocol
```suggestion
- **TLS features**: [client certificates](https://k6.io/docs/using-k6/protocols/ssl-tls/ssl-tls-client-certificates) and [configurable SSL/TLS versions and ciphers](https://k6.io/docs/using-k6/protocols/ssl-tls/ssl-tls-version-and-ciphers)
```

2022-07-26 12:00 UTC, MattDodsonEnglish requested changes
Thank you for these oxford commas.

The first comma looks good, but the second is breaking up the series in a way that is not correct.
Users can configure both SSL versions and ciphers, so "configurable" is an adjective for two coordinate nouns here.

Admittedly there's still ambiguity in this phrase, and punctuation alone can't fix it. But in this case, the hypertext enforces the grouping.

2022-08-11 15:40 UTC, na-- commented
Closing this, since the change requests haven't been addressed in a while and it's a very minor improvement.

2022-08-11 15:40 UTC, closed without merging