Fix VERSION_DETAILS does not contain the latest tag
grafana/k6 pull request #2691
Opened 2022-09-22 11:58 UTC by olegbespalov

# What?

Add a `--tags` flag to fetch all tags for the `git describe`.

# Why?

Without that flag k6's version details gets a previous flag.

Closes: #2676

2022-09-22 13:12 UTC, codebien approved these changes

2022-09-23 07:47 UTC, na-- requested changes
It seems like the same problem is also present in the Dockerfile: https://github.com/grafana/k6/blob/979378a08104f0f58a6aaf011a4c1ac764112437/Dockerfile#L5

2022-09-26 14:51 UTC, na-- approved these changes
:crossed_fingers:

2022-09-26 14:52 UTC, codebien approved these changes

2022-09-26 15:43 UTC, mstoykov approved these changes

2022-09-26 16:06 UTC, merged