Bump go to 1.19.1 and alpine to 3.16
grafana/k6 pull request #2696
Opened 2022-09-27 15:47 UTC by agilob

Upgrading go attempts to fix https://github.com/grafana/k6/issues/2474

2022-09-27 15:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/k6?pullRequest=2696) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/k6?pullRequest=2696) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/k6?pullRequest=2696) it.</sub>

2022-09-27 16:03 UTC, codebien requested changes
Hi @agilob, thanks for your contribution :bow: :tada: 

We would like to keep the `.x` version. I created a similar PR that I'm going to close #2695, but as you can see, there are more files to migrate. Can you migrate all of them, please?

2022-09-27 17:00 UTC, agilob commented
updated

2022-09-27 17:01 UTC, codebien requested changes
One more change required :pray:

2022-09-27 17:01 UTC, codebien commented on .github/workflows/lint.yml
> +          go-version: 1.18x.
```suggestion
          go-version: 1.19.x
```

2022-09-27 17:04 UTC, agilob commented
Sorry!

2022-09-27 17:22 UTC, codebien approved these changes
@agilob thanks for your contribution :clap: 

Does the new Docker image solve your main issue?

2022-09-27 18:32 UTC, agilob commented
We'll test it first thing tomorrow morning

2022-09-28 07:04 UTC, agilob commented
Tested this internally and it worked on our perf tests. pls merge

2022-09-28 09:00 UTC, mstoykov approved these changes

2022-09-28 09:01 UTC, merged