chore: use hkps
grafana/k6 pull request #2756
Opened 2022-11-04 01:22 UTC by kahirokunn

2022-11-07 08:12 UTC, na-- requested changes
Can you please edit just the README, not the super-old v0.22.0 release notes?

2022-11-08 00:48 UTC, kahirokunn commented
Done.

2022-11-08 08:24 UTC, na-- approved these changes
Thanks!

2022-11-08 12:41 UTC, mstoykov approved these changes
Thanks :bow:

2022-11-08 12:41 UTC, merged