fix: csv output for non indexable metrics
grafana/k6 pull request #2829
Opened 2022-12-21 12:34 UTC by leonyork

2022-12-21 12:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/k6?pullRequest=2829) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/k6?pullRequest=2829) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/k6?pullRequest=2829) it.</sub>

2023-01-05 15:09 UTC, aakashkaji approved these changes

2023-01-09 13:58 UTC, codebien requested changes
Hi @leonyork,
thanks for your contribution :bow:

I think we could unblock this PR if we extend the following unit test https://github.com/grafana/k6/blob/613fe8b56cf504ed85516b6a2584f8d9870f2725/output/csv/output_test.go#L212
providing the `vu` tag in one of the sample and enabling the VU system tag here:
https://github.com/grafana/k6/blob/613fe8b56cf504ed85516b6a2584f8d9870f2725/output/csv/output_test.go#L353

An integration test is still nice to have but we could address it in another PR.

2023-01-09 13:58 UTC, codebien commented on output/csv/output.go
> +
```suggestion
```

2023-01-12 21:05 UTC, leonyork commented
@codebien, thanks for the pointer to the unit test! I've updated that and removed the new line you suggested 🙂

2023-01-13 11:08 UTC, imiric approved these changes
Thanks for your work debugging and fixing this @leonyork! :clap: The excellent steps to reproduce it, and that separate repo were of great help :+1:

This looks great to me. It's an elegant and simple fix in an inelegant part of the codebase :sweat_smile:

Like @codebien says, we can add the integration test if needed later, once we merge all related PRs, or decide to just leave it with the unit test, since it does cover the change.

Don't worry about the CI failure, it's a known flaky test :disappointed:

2023-01-13 12:00 UTC, codebien approved these changes
LGTM, thanks @leonyork :bow:

2023-01-13 12:01 UTC, merged