Maintenance/GitHub actions 2
grafana/k6 pull request #2870
Opened 2023-01-23 11:56 UTC by olegbespalov

# What?

These changes finalize the removal of the deprecated Node 12.X from our CI

# Why?

Resolves #2763

2023-01-23 12:27 UTC, mstoykov approved these changes

2023-01-23 12:28 UTC, olegbespalov commented
`kentaro-m/auto-assign-action@v1.2.4` is still not at Node 16 :cry:

2023-01-23 12:40 UTC, olegbespalov commented
:thinking: but it should https://github.com/kentaro-m/auto-assign-action/pull/98

2023-01-23 14:54 UTC, oleiade approved these changes

2023-01-23 15:19 UTC, codebien submitted a review, later dismissed

2023-01-23 16:06 UTC, na-- requested changes
I :+1: the update, but :-1: using tags instead of specific commits. 

Using tags doesn't offer any security benefits if someone hacks the repos (or hacks an account that can push tags to these repos). They will be able to delete the old tag, push a new tag, and exfiltrate all of our secrets. Doing so with a commit is going to be quite difficult, they'd need a SHA1 collision with the same hash, given git's content-addressable nature...

2023-01-23 16:18 UTC, codebien commented
I'm not sure if it works as I expect  but it sounds like we should also limit with https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

2023-01-23 17:18 UTC, olegbespalov commented
@codebien sounds good/reasanoble, but should we maybe create a dedicated issue to limit tokens across all CI, WDYT :thinking:

2023-01-23 17:44 UTC, na-- approved these changes
Thanks for changing it, and yeah, permissions for different jobs sound awesome, I didn't know that was a thing!

2023-01-25 10:07 UTC, codebien approved these changes

2023-01-27 08:41 UTC, merged