chore: remove refs to deprecated io/ioutil
grafana/k6 pull request #3130
Opened 2023-06-19 04:31 UTC by testwill

2023-06-19 04:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/k6?pullRequest=3130) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/k6?pullRequest=3130) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/k6?pullRequest=3130) it.</sub>

2023-06-19 07:10 UTC, olegbespalov requested changes
Hi @calavera 

Thanks for the pull request! :relaxed: 

Before we can proceed with reviewing it, I'd like to ask you to adjust a few things:

* Ensure that the tests and linters are passed locally by running the following Makefile's targets (`make test` and `make ci-like-lint`)
* Provided a short description to the PR
* Revert a change under the `vendor` folder since it should be done only with the proper module update (`go modules`) .

Thanks!

2023-06-19 07:47 UTC, codebien commented
We should also add a `depguard` rule to our `golangci` config.

2023-06-20 09:49 UTC, olegbespalov commented
Hey @codebien 

> We should also add a depguard rule to our golangci config.

I briefly skimmed the https://github.com/OpenPeeDeeP/depguard, and wondering if we need it. However, let's open a separate issue (could you please do that since you raised it) where we could discuss a use case.

2023-06-29 14:43 UTC, imiric submitted a review, later dismissed
Thanks for the PR @testwill! :bow:

It LGTM, but as Oleg mentioned, the lint CI job should pass, and the way we agreed to do that internally is to add `nolint` directives to each case. Since most of these are in tests, we're fine ignoring these specific cases, instead of adding a global rule for all tests.

2023-07-12 13:15 UTC, mstoykov requested changes

2023-07-12 13:15 UTC, mstoykov commented on cmd/archive_test.go
> +			testScript, err := os.ReadFile(testCase.testFilename)
```suggestion
			testScript, err := os.ReadFile(testCase.testFilename) //nolint:forbidigo
```

2023-07-12 13:15 UTC, mstoykov commented on cmd/convert_test.go
> +	har, err := os.ReadFile("testdata/example.har")
```suggestion
	har, err := os.ReadFile("testdata/example.har") //nolint:forbidigo
```

2023-07-12 13:15 UTC, mstoykov commented on cmd/convert_test.go
> +	expectedTestPlan, err := os.ReadFile("testdata/example.js")
```suggestion
	expectedTestPlan, err := os.ReadFile("testdata/example.js") //nolint:forbidigo
```

2023-07-12 13:15 UTC, mstoykov commented on cmd/run_test.go
> +			testScript, err := os.ReadFile(path.Join("testdata", tc.testFilename))
```suggestion
			testScript, err := os.ReadFile(path.Join("testdata", tc.testFilename)) //nolint:forbidigo
```

2023-07-12 13:15 UTC, mstoykov commented on cmd/run_test.go
> +			testScript, err := os.ReadFile(path.Join("testdata", tc.testFilename))
```suggestion
			testScript, err := os.ReadFile(path.Join("testdata", tc.testFilename)) //nolint:forbidigo
```

2023-07-12 13:15 UTC, mstoykov commented on cmd/run_test.go
> +			testScript, err := os.ReadFile(path.Join("testdata", tc.testFilename))
```suggestion
			testScript, err := os.ReadFile(path.Join("testdata", tc.testFilename)) //nolint:forbidigo
```

2023-07-12 13:15 UTC, mstoykov commented on js/bundle_test.go
> +			prefix, err := os.MkdirTemp("", "k6_open_test")
```suggestion
			prefix, err := os.MkdirTemp("", "k6_open_test") //nolint:forbidigo
```

2023-07-12 13:15 UTC, mstoykov commented on js/console_test.go
> +							f, err := os.CreateTemp("", "")
```suggestion
							f, err := os.CreateTemp("", "") //nolint:forbidigo
```

2023-07-12 13:15 UTC, mstoykov commented on js/runner_test.go
> +	protoFile, err := os.ReadFile("../lib/testutils/httpmultibin/grpc_testing/test.proto")
```suggestion
	protoFile, err := os.ReadFile("../lib/testutils/httpmultibin/grpc_testing/test.proto") //nolint:forbidigo
```

2023-07-12 13:19 UTC, mstoykov approved these changes

2023-07-12 14:23 UTC, olegbespalov approved these changes
👍

2023-07-12 14:27 UTC, merged