Enable user headers in the reflect call in client.connect
grafana/k6 pull request #3242
Opened 2023-08-01 21:32 UTC by lirao

## What?

Add a parameter in `client.connect` to include user-provided headers in the reflect call.

## Why?

Some GRPC servers require a header to authenticate any call. The invoke command covers this use case, but the reflect command that's bundled in the connect command does not, which leads to authentication errors.

## Checklist

- [ ] I have performed a self-review of my code.
- [ ] I have added tests for my changes.
- [ ] I have run linter locally (`make ci-like-lint`) and all checks pass.
- [ ] I have run tests locally (`make tests`) and all tests pass.
- [ ] I have commented on my code, particularly in hard-to-understand areas.

## Related PR(s)/Issue(s)

2023-08-01 21:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/k6?pullRequest=3242) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/k6?pullRequest=3242) before we can accept your contribution.<br/><hr/>**Rao Li** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/k6?pullRequest=3242) it.</sub>

2023-08-02 10:58 UTC, codebien requested changes
Hey @lirao,
thanks for your contribution. :pray:  Can you please sign the CLA so we can accept your contribution?

2023-08-03 19:25 UTC, lirao commented
> Hey @lirao, thanks for your contribution. 🙏 Can you please sign the CLA so we can accept your contribution?

Hi, is it ok if someone on the k6 team make this change instead? I talked to my company's legal team and they don't allow me to sign this.

2023-08-03 19:28 UTC, lirao commented
Closing since I can't sign the CLA. Can someone else make this change instead?

2023-08-03 19:28 UTC, closed without merging