Upgrade xk6-browser to v1.1.0
grafana/k6 pull request #3355
Opened 2023-09-27 09:37 UTC by ankur22

## What?

This upgrades the [xk6-browser](https://github.com/grafana/xk6-browser) extension to [v1.1.0](https://github.com/grafana/xk6-browser/releases/tag/v1.1.0) in k6.

## Why?

Upgrade the extension in preparation for an upcoming release.

## Checklist

- [X] I have performed a self-review of my code.
- [ ] I have added tests for my changes. (NA)
- [X] I have run linter locally (`make ci-like-lint`) and all checks pass.
- [ ] I have run tests locally (`make tests`) and all tests pass.
- [ ] I have commented on my code, particularly in hard-to-understand areas. (NA)

## Related PR(s)/Issue(s)

2023-09-27 12:25 UTC, olegbespalov requested changes
@ankur22 I believe `go mod tidy` is missing

2023-09-27 12:26 UTC, ankur22 commented
> @ankur22 I believe go mod tidy is missing
Thanks @olegbespalov I was wondering why the deps linter was failing.

2023-09-27 12:28 UTC, ankur22 commented
> @ankur22 I believe go mod tidy is missing

@olegbespalov that didn't seem to help. No changes to commit after running `go mod tidy`.

2023-09-27 12:33 UTC, olegbespalov approved these changes

2023-09-29 09:54 UTC, codebien approved these changes

2023-09-29 09:55 UTC, merged