Remove the --logformat flag
grafana/k6 pull request #3389
Opened 2023-10-12 09:59 UTC by codebien

## What?

Removed the deprecated --logformat flag, the --log-format alternative should be used.

## Why?

Deprecation process.

2023-10-12 11:28 UTC, olegbespalov approved these changes

2023-10-12 11:33 UTC, olegbespalov requested changes
We need to migrate first: https://github.com/search?q=org%3Agrafana%20--logformat&type=code

2023-10-12 13:27 UTC, mstoykov commented
Given that this is still so widely used it might be worth postponing this a release or three after we remove it everywhere. 

This isn't really a problem we need to fix, but breaking user experiecne is not great if until yesterday we were telling them to a thing .

2023-10-12 17:48 UTC, olegbespalov commented
In my opinion, I don't think that we need to postpone this shrug:  We need to fix usage, and we have plenty of time.

However, I might think that following v0.48 could be one of the biggest from the perspective of breaking changes :sweat_smile:

2023-11-17 13:53 UTC, codebien commented
@olegbespalov the other parts have been changed, we should be now ready to merge this.

2023-11-17 13:55 UTC, olegbespalov approved these changes
🚀

2023-11-17 13:59 UTC, codebien commented
@oleiade as @mstoykov is on PTO, I add you as a reviewer.

2023-11-20 10:54 UTC, oleiade approved these changes

2023-11-20 10:55 UTC, merged