Warnings about options.cloud
grafana/k6 pull request #3407
Opened 2023-10-19 11:15 UTC by olegbespalov

## What?

This branch aims to start promoting the `options.cloud`. It's the state when it's safe to say to customers that it's safe to use. 

## Why?

These changes were originally part of #3348, but there is a chance that we could merge #3348, but we won't be ready to start offering usage of the `options.cloud`.

## Checklist

- [ ] I have performed a self-review of my code.
- [ ] I have added tests for my changes.
- [ ] I have run linter locally (`make lint`) and all checks pass.
- [ ] I have run tests locally (`make tests`) and all tests pass.
- [ ] I have commented on my code, particularly in hard-to-understand areas.

## Related PR(s)/Issue(s)

#3348

2023-10-20 09:34 UTC, codebien requested changes
Blocking as we will have to change the part related to https://github.com/grafana/k6/pull/3394 when it is merged.

But, at this point, I would like to make another attempt in considering to directly introduce the block for the cloud here.

Now we have this PR, @olegbespalov @andrewslotin do you still want to introduce the block there? This PR has a limited scope that fits the case.

2023-10-20 10:02 UTC, olegbespalov commented
If the question is "Do you still want to use `options.ext.loadimact` in the #3394?" then I do belive that using a legacy block is still the right thing since it guarantees atomically of the changes.

All parties are also aware of this problem of syncing between these two PRs, and we will do the right things depending on the pace.

I'm not sure this PR should be considered blocked, but I'm not against keeping it like that to stress the importance of some actions that could happen once the #3394 is merged. Also, I'm putting the note to the PR's first message to emphasize the importance of checking.

2023-10-20 10:15 UTC, codebien commented
>These changes were originally part of https://github.com/grafana/k6/pull/3348, but there is a chance that we could merge https://github.com/grafana/k6/pull/3348, but we won't be ready to start offering usage of the options.cloud.

I took the assumption that this PR was already blocked from the quoted condition to be verified. Isn't that? Do you intend to merge it without being sure that we are going to offer the usage of the option? Then eventually revert only this PR?

2023-10-20 10:21 UTC, olegbespalov commented
>I took the assumption that this PR was already blocked from the quoted condition to be verified. Isn't that? Do you intend to merge it without being sure that we are going to offer the usage of the option? Then eventually revert only this PR?

It's blocked because of that. That's true. Let me be explicit in the PR body.

But you wrote above:

>Blocking as we will have to change the part related to https://github.com/grafana/k6/pull/3394 when it is merged.

I was answering when I referring that I don't agree that it's blocked.

2023-10-20 10:28 UTC, olegbespalov commented
Also, I converted it to a daft since it waits for some internal decisions.

2024-02-05 11:02 UTC, codebien submitted a review, later dismissed

2024-02-08 15:58 UTC, mstoykov approved these changes
I do wonder if we should do this in the same version we introduce it.

Maybe have a version with it and let us see if there aren't any bugs will be better.

This will also let us go update it ... everywhere - which will be a major problem IMO with all of our documentation and examples

2024-02-08 16:37 UTC, codebien commented
>Maybe have a version with it and let us see if there aren't any bugs will be better.

Any bug on this specific feature will require us to hotfix. Plus, on the other side, I also see the risk that if we don't promote it then we may not get exposure and the users will not hit any eventual bugs.
So, considering that it isn't a blocker, and in any case, we have to fix it fast, I'm for just merging it.

2024-02-12 10:15 UTC, oleiade submitted a review, later dismissed
I align with @codebien ☝🏻 and think we should probably just merge it to get it some visibility indeed 🙇🏻

2024-02-19 14:47 UTC, mstoykov approved these changes

2024-02-19 15:23 UTC, codebien approved these changes

2024-02-27 09:25 UTC, merged