Add unit tests
grafana/k6 pull request #3517
Opened 2023-12-23 20:44 UTC by nilskch

## What?

I added some unit tests

## Why?

Hi, thank you very much for this awesome tool! I am using it for quite some time now and LOVE it. I was looking through the code base and I like it a lot and wanted to contribute some tests. 

<img width="629" alt="honest_work" src="https://github.com/grafana/k6/assets/52418412/dcfa4050-60c6-4fb1-8fa8-0b96d1cf2ac7">

I will eventually contribute more in the future!

## Checklist

- [X] I have performed a self-review of my code.
- [x] I have added tests for my changes.
- [x] I have run linter locally (`make lint`) and all checks pass.
- [ ] I have run tests locally (`make tests`) and all tests pass. (does fail locally but my tests pass)
- [x] I have commented on my code, particularly in hard-to-understand areas.

## Related PR(s)/Issue(s)

2023-12-27 13:53 UTC, joanlopez approved these changes
Thanks for your contribution @nilskch! I guess these bits are probably somehow covered by other tests, but I do think these shouldn't hurt, and increasing the coverage is generally positive rather than negative. Ah, it's definitely a good opportunity for you to start contributing to k6, so welcome! 👍🏻

2023-12-28 08:18 UTC, nilskch commented
@joanlopez, thank you very much! What do we do about the failing tests? I do not think they are related to my contribution.

2023-12-28 10:20 UTC, joanlopez commented
> @joanlopez, thank you very much! What do we do about the failing tests? I do not think they are related to my contribution.
> 
> EDIT: now they all pass

Yeah, I guess there's some flakiness. I re-ran the failed jobs twice and it end up working. 
Definitely not related with your contribution!

2024-01-04 14:06 UTC, codebien requested changes
Hey @nilskch.
thanks for your contribution :bow: 

Added some request changes.

2024-01-04 14:06 UTC, codebien commented on cloudapi/errors_test.go
> +	assert.Equal(t, errResp.Error(), expected)
```suggestion
	assert.Equal(t, expected, errResp.Error())
```

2024-01-04 14:06 UTC, codebien commented on cloudapi/errors_test.go
> +func TestError(t *testing.T) {
```suggestion
func TestErrorResponse_Error(t *testing.T) {
```

2024-01-04 14:29 UTC, nilskch commented on cloudapi/errors_test.go
> +	// this payload struct covers all edge cases that have not been covered before
This comment is confusing and I will remove it. This function was called somewhere else but it was not gracefully tested with all edge cases.

2024-01-04 14:31 UTC, nilskch commented
@codebien, I added your suggestions and squashed the commits.

2024-01-04 14:49 UTC, codebien approved these changes

2024-01-04 17:06 UTC, joanlopez approved these changes

2024-01-04 17:07 UTC, merged