Fix k6-insights enabled check
grafana/k6 pull request #3529
Opened 2024-01-11 10:37 UTC by Blinkuu

## What?

Use raw `Bool` instead of `ValueOrZero`.

## Why?

If the value hasn't been set by the user, the default value set to `true` in https://github.com/grafana/k6/pull/3398 was not respected.

## Checklist

- [x] I have performed a self-review of my code.
- [x] I have added tests for my changes.
- [x] I have run linter locally (`make lint`) and all checks pass.
- [x] I have run tests locally (`make tests`) and all tests pass.
- [x] I have commented on my code, particularly in hard-to-understand areas.

## Related PR(s)/Issue(s)

Fixes a bug introduced in https://github.com/grafana/k6/pull/3398.

2024-01-11 10:38 UTC, mstoykov approved these changes

2024-01-11 10:41 UTC, olegbespalov submitted a review, later dismissed

2024-01-11 10:43 UTC, vortegatorres submitted a review, later dismissed

2024-01-11 14:12 UTC, mstoykov requested changes
@Blinkuu Please fix the tests. This likely is due to them now having tracing enabled by default. You can likely just disable it specifically for those tests.

2024-01-12 15:44 UTC, mstoykov approved these changes

2024-01-12 16:06 UTC, olegbespalov approved these changes

2024-01-12 16:06 UTC, merged