Lock module resolution after initialization
grafana/k6 pull request #3680
Opened 2024-04-08 15:19 UTC by mstoykov

## What?

Make it an error to try to resolve not previously resolved modules, after initialization

## Why?

Partly because it should be given how we make k6 work and want `k6 archive` and `k6 cloud` to "just work".

Partly because this ended up being the only not completely hackish way to know that we are past the initialization state which was needed in order to make a warning only in the init context. 

## Checklist

- [X] I have performed a self-review of my code.
- [X] I have added tests for my changes.
- [X] I have run linter locally (`make lint`) and all checks pass.
- [X] I have run tests locally (`make tests`) and all tests pass.
- [X]I have commented on my code, particularly in hard-to-understand areas.

## Related PR(s)/Issue(s)

2024-04-19 14:58 UTC, codebien requested changes
The logic LGTM, just a request for improving the comment.

2024-04-19 14:58 UTC, codebien commented on js/modules/resolution.go
> +// This to facilitate loading all the modules a test needs in it's initilization the same as with openning files.
```suggestion
// Lock locks the module's resolution from any further new resolving operation. It means that it relays only its internal cache and on the fact that it has already seen previously the module during the initialization. 
// It is the same approach used for opening file operations.
```
I had to read several times to get the context. I prefer if we try to clarify a bit.

2024-04-19 15:02 UTC, codebien approved these changes

2024-04-19 15:14 UTC, mstoykov commented on js/modules/resolution.go
> +// Lock locks the module's resolution from any further new resolving operation. It means that it relays only its internal cache and on the fact that it has already seen previously the module during t
```suggestion
// Lock locks the module's resolution from any further new resolving operation.
// It means that it relays only its internal cache and on the fact that it has already
// seen previously the module during the initialization. 
```

2024-04-22 07:09 UTC, joanlopez approved these changes

2024-04-22 07:11 UTC, merged